server:
  port: 8120 # 端口号
spring:
  application:
    name: service_oss # 应用名称
  profiles:
    active: dev # 环境配置
# mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 阿里云oss
aliyun:
  oss:
    keyId:
    keySecret:
    bucketName: xycollege-file
    endpoint: oss-cn-beijing.aliyuncs.com