server:
  port: 8170 # 端口号
#  tomcat:
#    max-threads: 10 # 修改tomcat最大并发值为10，默认是200。（超过最大并发值，开始执行同步策略）
spring:
  application:
    name: service-trade # 应用名称
  profiles:
    active: dev # 环境配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #    url: jdbc:mysql://192.168.1.37:3306/xy_edu?useUnicode=true&characterEncoding=UTF-8
    url: jdbc:mysql://192.168.43.193:3306/xy_trade?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 333
  jackson: #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.43.193:8848 # 注册中心nacos服务地址
    #spring:
    # cloud:
    sentinel:
      transport:
        port: 8081 #跟控制台交流的端口，随意指定一个未使用的端口即可
        dashboard: 127.0.0.1:8080 # 指定sentinel控制台服务的地址
  #spring:
  redis:
    host: 192.168.43.193
    port: 6379
    database: 0
    #    password:  #默认为空
    lettuce: # 连接池配置
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0
#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # mybatis-plus:
  mapper-locations: classpath:cn/andylhl/xy/service/trade/mapper/xml/*.xml
# 配置负载均衡策略（对要调用的下游微服务进行指定配置）
service-oss:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
# ribbon相关配置
ribbon:
  MaxAutoRetries: 0 # 同一实例最大重试次数，不包括首次调用，默认0
  MaxAutoRetriesNextServer: 1 # 重试其他实例的最大重试次数，不包括首次所选的server，默认1
  ConnectTimeout: 10000 #连接建立的超时时长，默认1秒
  ReadTimeout: 10000 #处理请求的超时时间，默认为1秒
# 开启feign对ribbon的支持
feign:
  sentinel:
    enabled: true
# 支付宝配置信息
alipay:
  serverUrl: https://openapi.alipaydev.com/gateway.do
  appId: 2021000117605472
  privateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCo5rgON5CDbEWcAoKpdCTsF6t3PKuKYypS1RsCKrE6GiizbVYRZKf0coRTlqn72/64ST2gCAQODmH3kPnLckLltK9CdJADOxPZrdv+A0RrLaOcQ2PPLJG0W/vkwy6dIuEfHujZbXGQgpS3hMBO/r0CpSS/pbGmm2qwASrBqKeKU9ix6+p19or3vuRDnJ512itl3q1TqnYY34GSJ/ItZ7H6ivMbfNRCLromXslrelZ0bbedHuU1W9cEbfGCEWeBCH1Ov92gpB7eQUdHRl8FzjWv1jv++dA+l9IiUNMyr6SsJLlUnaJPH6g19fEaE9VsQvH0Rq5S4ih1o6YVsI8p7rdjAgMBAAECggEAOeYtfiIqFgNNsXdi1zgLWCudCdjwbRYlchO/mHSOIH7LKQb4FCpPMQr4tbbWOpJltULWLz/QNAlWKAm4t7dJm3jfA4b1v0XHPj3NRjxUffE9PtoTIvgCUrOdnAQUvKUySvrLk41i+sjotih5zBqjLH70JAZm6dgpMICV6aEpHc+lEn4B4aegLYy+fnfrxZzpGaN+gt1U7Hj8q6MLihbT/M+RArn3EsLM4t9SH3hPQtN9xCcGV3R/exP6y3SIVVUREEkYeu02JEImu1ARe5ruBl3FgEdvEAQoMkpq3nosu3XTNMLZ/OihzZXaCItnKG1Q6kAw6rIHQkDkkzqc4eZyYQKBgQDmJBelpmTWhKFn21oYFywzjXTdse5U/vuuA+q4xRciEB/WSFv/tux1g030GWOv7mZFiGNafSV5sAwFaMhkQR8wfdhhuKMq9+XSM1QcHPoduyblJpgiqlKqr+WcgXwh3BEHEtajPUNnhNe8QTGIGSFvBmueFU1WsLc2RKZaTB43uwKBgQC74RdtOKjQ2vtBQN/AFFSxDaqxRXuXJ9DOd2JQHb3cswVhTikJdD4OVQfMDxS6UKtMhvJv9WquAtLByMDGyhI0HnrEWvuVvNSe1dWgyQJLCURAJVUsgL99BK2QnH76SDgs7cXTVqgCioQDgJobU07NeunFwLRFJtm3fV1AgZ0geQKBgE1Kbc6qNU9+N57jojxY+/VMWqVh7oMJJ4lns1rehkhgVfDnWE5nJr7InFOQe1RIonxTs9peEUnu//qJGFPjMxBcE2GuWs5BdyPDLUpLyQxXIFbxQULTJPRCIsEPE5tjhyxy/TbRimOnz7RfyLzGg93/sADlcpXcv4swPxYwXi2lAoGAfJtbeDsd6/dwsOSgAbr6OLuBvDUDNUtY97bCY7R2Ggw5w0GdggGwrrzCgRp3euLJ2eWeoZa5fFOvCItnH/EhhaO5dMWLGtK0iev01cC7Xpz0wT6BcRSq6/XQT5sbtE91woaor/RHVfgcel4u13S3TRz6MwgOB9cuir4AvSm51rECgYAFv2eBKoFtgigcfU1puISei96o1jenhrZtG5SAyr0Weds4xvM86hePQOvWQnlOl/nAOfVC8HH+K6vaTsDM/aRBB6QDoFwtjTB8+HKdgvlSSe8JQi8oztb/tKh7X7KwXNCF4mfJoPiuR11dRxJ0+utD2P2B6eg4EJfVDRBUOjec1A==
  format: json
  charset: utf-8
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlA1v3zIic1Xtr4QGNGJ1iwrNZ67O8o6D+wIWFh8vgzGWz7SrCGtc2zJIQrxyvzVPrZlduvHIeYBroYX4m6SgjxJ8kLjmRGna4dh4Ht/zZMSCtRr8HVyg2XawBPMU2Jwut1OcgfeHFso1jS7yVva/lkLKar8RgvgCjSPzpRuveIquuzoDGSUE450g9KgIBpqXlro9mUKiHMCLAtbhyATI5BKqQei7qI6d/cBuvhohaxhZ/i6ttLCgNMedA3QnzNZt4sxNWJ+jyLBlalCt7V4rhMrPJVanfSOD3HoMI+25Rc9bPDGOY0Ndbz5dwAdHTQ4dphtLBEuwGpfl3a1nGffejQIDAQAB
  signType: RSA2
  notifyUrl: http://xycollege.free.idcfengye.com/api/trade/alipay/callback/notity
  returnUrl: http://127.0.0.1:8170/api/trade/alipay/callback/return