server:
  port: 8150 # 端口号
spring:
  application:
    name: service-sms # 应用名称
  profiles:
    active: dev # 环境配置
  #spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.43.193:8848 # 注册中心nacos服务地址
  #spring:
  redis:
    host: 192.168.43.193
    port: 6379
    database: 0
    #    password:  #默认为空
    lettuce: # 连接池配置
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0
  #spring:
  mail:
    host: smtp.qq.com
    username: 2432707158@qq.com # 发件人的邮箱
    password: ajlzgiopwcnheaie  # 发件邮箱的授权码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
# mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl