server:
  port: 8130 # 端口号
spring:
  application:
    name: service-vod # 应用名称
  profiles:
    active: dev # 环境配置
  #spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.37:8848 # 注册中心nacos服务地址
# mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 阿里云oss
aliyun:
  vod:
    keyId: LTAI4GEc8neP1KfNucXgemEw
    keySecret: UAl3MFnZ9nMkV0Nn3tshgEgUGHsfBA
    templateGroupId: 123 #转码模板组id
    workflowId: 456 #工作流id